version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: todo-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
