[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean install"

[deploy]
startCommand = "java -jar target/*.jar"
healthcheckPath = "/swagger-ui.html"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 